#!/usr/bin/env node
/**
 * Import LimeZu Modern Office asset pack into MeetKai Room Editor catalog.
 *
 * Scans Modern_Office_Singles_32x32/ PNG files, verifies dimensions divisible by TILE_SIZE,
 * and generates PaletteEntry objects matching tilePaletteManifest.ts format.
 *
 * NO EXTERNAL DEPENDENCIES — uses only Node built-ins.
 *
 * Usage: node scripts/importLimeZuAssets.mjs
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const repoRoot = path.resolve(__dirname, '..');

const SINGLES_DIR = path.join(repoRoot, 'client/public/assets/tilesets/modern-office/Modern_Office_Singles_32x32');
const OUTPUT_MANIFEST = path.join(repoRoot, 'client/src/data/limezu-office-manifest.ts');
const TILE_SIZE = 32;
const CATEGORY = 'furniture'; // LimeZu singles are furniture for now; can be split later

// Helper: read PNG IHDR chunk to get width/height (no external deps)
function readPngDimensions(filePath) {
  try {
    const buffer = fs.readFileSync(filePath);
    // PNG signature: 89 50 4E 47 0D 0A 1A 0A (8 bytes)
    // IHDR chunk: length (4 bytes) + 'IHDR' (4 bytes) + data (13 bytes: w,h,bit,color,comp,filter,interlace)
    // Width at bytes 16-19 (big-endian uint32)
    // Height at bytes 20-23 (big-endian uint32)
    if (buffer.length < 24 || buffer[0] !== 0x89 || buffer[1] !== 0x50) {
      return null;
    }
    const width = buffer.readUInt32BE(16);
    const height = buffer.readUInt32BE(20);
    return { width, height };
  } catch (err) {
    console.error(`  ❌ Error reading ${path.basename(filePath)}:`, err.message);
    return null;
  }
}

// Helper: compute standard 64×96 padding-canvas crop (convention from tilePaletteManifest.ts)
// All Modern_Office_Singles are exported on 64×96 canvas, so use that to estimate tiles.
// For simplicity, assume bottom-anchored 32×64 content → srcY=32, tilesW=2, tilesH varies.
// This is a conservative estimate; manual refinement may be needed for specific pieces.
function estimateTileDimensions(width, height) {
  // Expected: 64×96 canvas
  if (width !== 64 || height !== 96) {
    // If unexpected dimensions, fall back to simple tile count
    return {
      srcX: 0,
      srcY: Math.max(0, height - 64),
      tilesW: Math.ceil(width / TILE_SIZE),
      tilesH: Math.ceil(Math.min(64, height) / TILE_SIZE),
    };
  }
  // Standard 64×96: 2 tiles wide, height varies (1-3 tiles)
  return {
    srcX: 0,
    srcY: 32, // Content assumed to occupy bottom 64px (2 rows)
    tilesW: 2,
    tilesH: 2,
  };
}

// Main
async function main() {
  console.log('🔍 Scanning LimeZu Modern Office singles...\n');

  // List all PNG files
  const files = fs.readdirSync(SINGLES_DIR)
    .filter(f => f.endsWith('.png'))
    .sort();

  if (files.length === 0) {
    console.error(`❌ No PNG files found in ${SINGLES_DIR}`);
    process.exit(1);
  }

  console.log(`📦 Found ${files.length} assets. Analyzing bounding boxes...\n`);

  const entries = [];
  const anomalies = [];

  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    const filePath = path.join(SINGLES_DIR, file);
    const relPath = `/assets/tilesets/modern-office/Modern_Office_Singles_32x32/${file}`;

    // Extract index from filename
    const match = file.match(/Modern_Office_Singles_32x32_(\d+)\.png/);
    const idx = match ? parseInt(match[1], 10) : i + 1;
    const id = `limezu-office-${String(idx).padStart(3, '0')}`;
    const label = `LimeZu Office ${idx}`;

    process.stdout.write(`\r  [${i + 1}/${files.length}] ${id}`);

    const dims = readPngDimensions(filePath);
    if (!dims) {
      anomalies.push({ file, reason: 'Failed to read PNG header' });
      continue;
    }

    const { width, height } = dims;

    // Check for anomalies: dimensions not integer-multiple of TILE_SIZE
    if (width % TILE_SIZE !== 0 || height % TILE_SIZE !== 0) {
      anomalies.push({
        file,
        reason: `Dimensions ${width}×${height} not divisible by TILE_SIZE (32)`,
      });
    }

    const tiles = estimateTileDimensions(width, height);

    entries.push({
      id,
      label,
      category: CATEGORY,
      src: relPath,
      srcX: tiles.srcX,
      srcY: tiles.srcY,
      tilesW: tiles.tilesW,
      tilesH: tiles.tilesH,
    });
  }

  console.log('\n');

  // Report anomalies
  if (anomalies.length > 0) {
    console.log(`⚠️  ${anomalies.length} anomalies found:\n`);
    anomalies.forEach(({ file, reason }) => {
      console.log(`   • ${file}: ${reason}`);
    });
    console.log();
  }

  // Generate manifest TypeScript code
  const manifestCode = `// Auto-generated by scripts/importLimeZuAssets.mjs
// LimeZu Modern Office pack (${entries.length} assets)
//
// WARNING: Tile dimensions (srcX, srcY, tilesW, tilesH) are estimated from
// the standard 64×96 padding-canvas convention. For pieces with actual
// content outside the default bottom-anchored 2×2 region, manual adjustment
// may be needed (e.g., tall plants → tilesH: 3, srcY: 0).
//
// License: See client/public/assets/tilesets/modern-office/limezu/LICENSE.txt

import { PaletteEntry } from './tilePaletteManifest';

export const LIMEZU_OFFICE_ENTRIES: PaletteEntry[] = [
${entries.map(e => `  {
    id: '${e.id}',
    label: '${e.label}',
    category: '${e.category}',
    src: '${e.src}',
    srcX: ${e.srcX},
    srcY: ${e.srcY},
    tilesW: ${e.tilesW},
    tilesH: ${e.tilesH},
  },`).join('\n')}
];
`;

  fs.writeFileSync(OUTPUT_MANIFEST, manifestCode, 'utf8');
  console.log(`✅ Generated manifest: ${path.relative(repoRoot, OUTPUT_MANIFEST)}`);
  console.log(`   ${entries.length} entries (all with estimated tile dimensions)`);

  if (anomalies.length > 0) {
    console.log(`\n⚠️  ${anomalies.length} anomalies (dimensions not divisible by TILE_SIZE):`);
    anomalies.forEach(({ file, reason }) => {
      console.log(`   • ${file}: ${reason}`);
    });
    console.log(`   These entries were still added to the manifest but may need per-file verification.`);
  }

  console.log(`\n📝 Next steps:`);
  console.log(`   1. Review ${path.basename(OUTPUT_MANIFEST)}`);
  console.log(`   2. For tall/wide pieces, manually adjust tilesW/tilesH in the manifest`);
  console.log(`   3. Add LIMEZU_OFFICE_ENTRIES to tilePaletteManifest.ts: [...TILE_PALETTE, ...LIMEZU_OFFICE_ENTRIES]`);
  console.log(`   4. Test in Room Editor`);
}

main().catch(err => {
  console.error('❌ Fatal error:', err);
  process.exit(1);
});
